/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/3d/torrus.glb --printgraph 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/torrus.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Torus002.geometry} material={materials.Material} />
    </group>
  )
}

useGLTF.preload('/torrus.glb')
